name: questionario
description: Questionario para programadores.
version: 0.0.1+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.1
  http:
  provider:
  equatable:

dev_dependencies:
  flutter_launcher_icons:
  flutter_test:
    sdk: flutter
  test:
  mockito:
  faker:
  

flutter:
  uses-material-design: true
  assets:
    - lib/iu/imagens/

flutter_icons:
  ios: true
  android: true
  image_path_android: lib/iu/imagens/icones/android.png
  image_path_ios: lib/iu/imagens/icones/ios.png
  adaptive_icon_background: lib/iu/imagens/icones/fundo.png
  adaptive_icon_foreground: lib/iu/imagens/icones/frente.png